version: 1  
llm:
  openai:
    model: 'gpt-35-turbo'
    temperature: 0
  gemini:
    model: 'gemini-1.5-flash'
    temperature: 0.7
    max_retries: 2

db:
  neo4j:
    examples_file: 'graph_examples.json'
    queries_file: 'graph_queries.json'
    prompts_file: 'graph_prompts.json'


use_llm: gemini
use_db: neo4j



