version: 1
disable_existing_loggers: false
formatters:
    standard:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        formatter: standard
        level: INFO
    file:
        class: logging.FileHandler
        formatter: standard
        filename: logs/app.log
        backupCount: 2
        level: DEBUG

root:
    handlers: [console, file]
    level: DEBUG